import 'package:flutter/material.dart';

class Atividade {
  final int id;
  final double altura;
  final Color cor;
  final String descricao;

  Atividade(this.id, this.cor, this.altura, this.descricao);

  get assetImagem {
    return 'assets/ativs/listaAtiv${id.toString().padLeft(3,'0')}.JPG';
  }
}

class ServAtividades{

  final List<Atividade> _atividades = [
    Atividade(1 , Colors.pink, 170, 'Fazer atividades em contato com a natureza'),
    Atividade(2	, Colors.black, 170, 'Observar a forma das nuvens'),
    Atividade(3	, Colors.black, 110, 'Conversar com pessoas'),
    Atividade(4	, Colors.black, 110, 'Fazer as unhas'),
    Atividade(5	, Colors.white, 170, 'Andar de patins ou roller'), 
    Atividade(6	, Colors.white, 170, 'Fazer algo nostálgico (p. ex., ouvir músicas da infância)'),
    Atividade(7	, Colors.black, 110, 'Observar o mar'),
    Atividade(8	, Colors.white, 110, 'Caminhar/correr'),
    Atividade(9	, Colors.black, 170, 'Alimentar ou observar os pássaros'),
    Atividade(10, Colors.white, 150, 'Encontro com amigos'),
    Atividade(11, Colors.black, 170, 'Cozinhar'),
    Atividade(12,	Colors.black, 170, 'Construir um castelo de areia'),
    Atividade(13,	Colors.black, 170, 'Yoga/pilates'),
    Atividade(14,	Colors.black, 170, 'Comprar presentes'),
    Atividade(15,	Colors.black, 170, 'Testar uma nova receita'),
    Atividade(16,	Colors.black, 170, 'Consertar coisas em casa'), 
    Atividade(17,	Colors.black, 170, 'Assistir televisão, séries e vídeos'),  
    Atividade(18,	Colors.black, 170, 'Fazer churrasco com amigos/família'), 
    Atividade(19,	Colors.black, 170, 'Relaxar em um SPA, sauna, banheira'),
    Atividade(20,	Colors.black, 170, 'Jogar tênis/beachtenis'),
    Atividade(21,	Colors.black, 170, 'Falar ao telefone ou fazer uma chamada de vídeo'),  
    Atividade(22,	Colors.black, 170, 'Organizar armários'), 
    Atividade(23,	Colors.black, 170, 'Tocar um instrumento musical'), 
    Atividade(24,	Colors.black, 170, 'Ir ao cinema, teatro, show'), 
    Atividade(25,	Colors.black, 170, 'Acender velas e incensos'),
    Atividade(26,	Colors.black, 170, 'Passar um tempo sozinho'), 
    Atividade(27,	Colors.black, 170, 'Planejar as férias'),
    Atividade(28,	Colors.black, 170, 'Viajar'), 
    Atividade(29,	Colors.black, 170, 'Ir à praia'), 
    Atividade(30,	Colors.black, 170, 'Pebolim/Futebol de botão'),
    Atividade(31,	Colors.black, 170, 'Participar de trabalho voluntário'), 
    Atividade(32,	Colors.black, 170, 'Ir ao zoológico, aquário'),
    Atividade(33,	Colors.black, 170, 'Montar quebra cabeça, fazer palavras cruzadas'),
    Atividade(34,	Colors.black, 170, 'Fazer doações para caridade'),
    Atividade(35,	Colors.black, 170, 'Observar o por ou o nascer do sol'),
    Atividade(36,	Colors.black, 170, 'Escutar rádio, música ou podcast'),
    Atividade(37,	Colors.black, 170, 'Fazer trabalhos manuais'),
    Atividade(38,	Colors.black, 170, 'Andar a cavalo'),
    Atividade(39,	Colors.black, 170, 'Fazer tarefas domésts'),
    Atividade(40,	Colors.black, 170, 'Jogar futebol'),
    Atividade(41,	Colors.black, 170, 'Ler'),
    Atividade(42,	Colors.black, 170, 'Jogar cartas ou jogos de tabuleiro'),
    Atividade(43,	Colors.black, 170, 'Passar hidratante/protetor solar'),
    Atividade(44,	Colors.black, 170, 'Cuidar do jardim ou piscina'),
    Atividade(45,	Colors.black, 170, 'Acampar'),
    Atividade(46,	Colors.black, 170, 'Passear/brincar com o animal de estimação'),
    Atividade(47,	Colors.black, 170, 'Ir ao salão de beleza ou estética'),
    Atividade(48,	Colors.black, 170, 'Descartar lixo eletrônico'),
    Atividade(49,	Colors.black, 170, 'Ir a festas'),
    Atividade(50,	Colors.black, 170, 'Organizar ou olhar fotos ou vídeos pessoais'),
    Atividade(51,	Colors.black, 170, 'Fazer compras'),
    Atividade(52,	Colors.black, 170, 'Ficar aconchegado em uma coberta'),
    Atividade(53,	Colors.black, 170, 'Ensinar habilidades especiais'),
    Atividade(54,	Colors.black, 170, 'Jogar jogos eletrônicos'),
    Atividade(55,	Colors.black, 170, 'Fazer trilhas'),
    Atividade(56,	Colors.black, 170, 'Enviar mensagem de texto'),
    Atividade(57,	Colors.black, 170, 'Pescar'),
    Atividade(58,	Colors.black, 170, 'Cantar no chuveiro ou ir em um karaokê'), 
    Atividade(59,	Colors.black, 170, 'Vestir uma roupa que me sinta bem'),
    Atividade(60,	Colors.black, 170, 'Colecionar itens (p. ex., selos, figurinhas, moedas)'),
    Atividade(61,	Colors.black, 170, 'Jogar vôlei'),
    Atividade(62,	Colors.black, 170, 'Olhar ou interagir nas redes sociais'),
    Atividade(63,	Colors.black, 170, 'Conviver com a família'),
    Atividade(64,	Colors.black, 170, 'Aprender uma nova língua'),
    Atividade(65,	Colors.black, 170, 'Trabalhar'),
    Atividade(66,	Colors.black, 170, 'Lavar ou consertar o carro ou bicicleta'),
    Atividade(67,	Colors.black, 170, 'Dormir'),
    Atividade(68,	Colors.black, 170, 'Dirigir'),
    Atividade(69,	Colors.black, 170, 'Navegar na internet'),
    Atividade(70,	Colors.black, 170, 'Doar sangue'),
    Atividade(71,	Colors.black, 170, 'Meditar'),
    Atividade(72,	Colors.black, 170, 'Tomar sorvete'),
    Atividade(73,	Colors.black, 170, 'Organizar meu local de trabalho'),
    Atividade(74,	Colors.black, 170, 'Ballet, jazz'),
    Atividade(75,	Colors.black, 170, 'Escrever poemas, blog, contos, etc.'),
    Atividade(76,	Colors.black, 170, 'Engraxar os sapatos'),
    Atividade(77,	Colors.black, 170, 'Dançar'), 
    Atividade(78,	Colors.black, 170, 'Boxe/luta'),
    Atividade(79,	Colors.black, 170, 'Ouvir música clássica'),
    Atividade(80,	Colors.black, 170, 'Fotografar'),
    Atividade(81,	Colors.black, 170, 'Ver vídeos engraçados no Youtube'),
    Atividade(82,	Colors.black, 170, 'Ir à missa, templo, sinagoga, rezar em casa'),
    Atividade(83,	Colors.black, 170, 'Ler jornal ou revistas'),
    Atividade(84,	Colors.black, 170, 'Planejar e dar uma festa'),
    Atividade(85,	Colors.black, 170, 'Dança de salão'),
    Atividade(86,	Colors.black, 170, 'Frequentar aulas de teatro'),
    Atividade(87,	Colors.black, 170, 'Andar de bicicleta'),
    Atividade(88,	Colors.black, 170, 'Comprar novos itens de papelaria'),
    Atividade(89,	Colors.black, 170, 'Alongamento'),
    Atividade(90,	Colors.black, 170, 'Desligar dispositivos eletrônicos por uma hora'),
    Atividade(91,	Colors.black, 170, 'Ir a um jogo de futebol (ou vôlei, basquete, etc.)'),
    Atividade(92,	Colors.black, 170, 'Trabalhos de marcenaria'),
    Atividade(93,	Colors.black, 170, 'Planejar uma boa surpresa para alguém'), 
    Atividade(94,	Colors.black, 170, 'Fazer musculação'),
    Atividade(95,	Colors.black, 170, 'Fazer uma seleção de músicas animadas'),
    Atividade(96,	Colors.black, 170, 'Jogar basquete'),
    Atividade(97,	Colors.black, 170, 'Desenhar ou colorir'),
    Atividade(98,	Colors.black, 170, 'Participar de um coral'),
    Atividade(99,	Colors.black, 170, 'Realizar uma tarefa pendente (p. ex., responder a um e-mail)'),
     Atividade(100,	Colors.black, 170, 'Passear de barco, balsa, lancha'),
     Atividade(101,	Colors.black, 170, 'Observar decolagens/aterrisagens no aeroporto'),
     Atividade(102,	Colors.black, 170, 'Planejar minha carreira'),
     Atividade(103,	Colors.black, 170, 'Compor uma música'),
     Atividade(104,	Colors.black, 170, 'Ir a uma biblioteca'),
     Atividade(105,	Colors.black, 170, 'Natação/hidroginástica'),
     Atividade(106,	Colors.black, 170, 'Fazer tricô, croché'),
     Atividade(107,	Colors.black, 170, 'Descansar em uma rede'),
     Atividade(108,	Colors.black, 170, 'Costurar'),
     Atividade(109,	Colors.black, 170, 'Conversar com vizinhos'),
     Atividade(110,	Colors.black, 170, 'Fazer um piquenique'),
     Atividade(111,	Colors.black, 170, 'Usar aplicativos de relacionamentos, ir a um encontro'),
     Atividade(112,	Colors.black, 170, 'Passear com as crianças'),
     Atividade(113,	Colors.black, 170, 'Cross fit/Treinamento funcional'),
     Atividade(114,	Colors.black, 170, 'Caminhar na praia'),
     Atividade(115,	Colors.black, 170, 'Enviar uma carta ou cartão postal'),
     Atividade(116,	Colors.black, 170, 'Praticar mergulho ou snorkel'),
     Atividade(117,	Colors.black, 170, 'Observar meus filhos brincarem'),
     Atividade(118,	Colors.black, 170, 'Andar de skate'),
     Atividade(119,	Colors.black, 170, 'Fazer origamis'),
     Atividade(120,	Colors.black, 170, 'Jogar pingue-pongue'),
     Atividade(121,	Colors.black, 170, 'Receber ou fazer uma massagem'),
     Atividade(122,	Colors.black, 170, 'Empinar pipa'),
     Atividade(123,	Colors.black, 170, 'Almoçar ou jantar fora'),
     Atividade(124,	Colors.black, 170, 'Relaxar na piscina'),
     Atividade(125,	Colors.black, 170, 'Tomar café ou chá com amigos'),
     Atividade(126,	Colors.black, 170, 'Usar itens especiais (p. ex., porcelana fina, joias)'),
     Atividade(127,	Colors.black, 170, 'Surfar'),
     Atividade(128,	Colors.black, 170, 'Ir a um local público e observar pessoas'),
     Atividade(129,	Colors.black, 170, 'Olhar vitrines'),
     Atividade(130,	Colors.black, 170, 'Dar uma volta pelo bairro'),
     Atividade(131,	Colors.black, 170, 'Fazer a barba'),
     Atividade(132,	Colors.black, 170, 'Fazer bolhas de sabão'),
     Atividade(133,	Colors.black, 170, 'Comprar móveis novos para a casa'),
     Atividade(134,	Colors.black, 170, 'Fazer um test drive em um carro novo'),
     Atividade(135,	Colors.black, 170, 'Jogar paintball'),
     Atividade(136,	Colors.black, 170, 'Remodelar os móveis da casa'),
     Atividade(137,	Colors.black, 170, 'Visitar familiares'),
  ];

  get atividades {
    return [..._atividades];
  }
}